# -*- coding: utf-8 -*-
"""cw_session 4_25bcon1107.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6Nue7vlzltIqQkxyCYAAGemxoRYbpC_

Adesh jain
"""

n =5
fact = 1
for i in range(1, n +1):
  fact = fact* i
  print("factorial of ",n, "=", fact)

print("adesh")

class Student:
    def __init__(self, name, roll, marks):
        self.name = name
        self.roll = roll
        self.marks = marks


s1 = Student("ADESH", 101, "60")

print("Name:", s1.name)
print("Roll:", s1.roll)
print("Marks:", s1.marks)